{"uuid": "0cdad462-ef6d-4062-ae35-9ef560157dbe", "children": ["ea8dce9c-8a48-4032-b7ab-98d568665e99"], "befores": [{"name": "setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home\n\n", "trace": "  File \"c:\\users\\selfg\\pycharmprojects\\selleniumpythonproject\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\selfg\\pycharmprojects\\selleniumpythonproject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\selfg\\pycharmprojects\\selleniumpythonproject\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\selfg\\PycharmProjects\\selleniumPythonProject\\PytestPrograms\\test_selenium_fixture.py\", line 10, in setup\n    driver = webdriver.Chrome(service=s)\n  File \"c:\\users\\selfg\\pycharmprojects\\selleniumpythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 70, in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"c:\\users\\selfg\\pycharmprojects\\selleniumpythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 90, in __init__\n    self.service.start()\n  File \"c:\\users\\selfg\\pycharmprojects\\selleniumpythonproject\\venv\\lib\\site-packages\\selenium\\webdriver\\common\\service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1648822692985, "stop": 1648822692986}], "start": 1648822692985, "stop": 1648822693139}